### ISSUE TITLE
Support LanguageClient-neovim

### ISSUE THREAD

**Issue by hackel** [prabirshrestha/asyncomplete.vim#17]
I wasn't sure if this project supported LanguageClient-neovim and its many available language servers (or if it would even be possible), but that would be great.  Looks like there's a vim-specific solution here, but it doesn't support completion yet: https://github.com/tjdevries/nvim-langserver-shim

**Comment by prabirshrestha** [comment]
You should be able to configure asyncomplete.vim for LanguageClient-neovim similar to how deoplete and ncm is supported. Currently it doesn't work out of the box.

nvim-langserver-shim's author is planning to rewrite it in lua. But here too you should be able to use asyncomplete.vim depending on its apis.

I'm working on writing lsp plugin in full vimscript, more info at https://github.com/prabirshrestha/vim-lsp/pull/10. My priority is to get this working with asyncomplete for now.

**Comment by hackel** [comment]
Thanks for clarifying.  Looks like an ambitious project!

**Comment by prabirshrestha** [comment]
Auto complete for LSP is now supported by [asyncomplete-lsp.vim](https://github.com/prabirshrestha/asyncomplete-lsp.vim). You can find more details at https://github.com/prabirshrestha/asyncomplete.vim#language-server-protocol-lsp

If @autozimu would like to add [asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim) support in LanguageClient-neovim I'm more than happy to help out.

For now I'm closing this since asyncomplete.vim doesn't ship with any sources.
