### ISSUE TITLE
Tags?

### ISSUE THREAD

**Issue by Taverius** [prabirshrestha/asyncomplete.vim#19]
Any plans to import the NCP tag completion functionality?

Yes, I'm asking/begging because I'm not capable of doing it myself ^^

**Comment by prabirshrestha** [comment]
I'm not familiar with NCP tags. Do you have links? Or did you mean just normal vim tags.

Please add links to repos so I can look into creating completion source based on it.

**Comment by Taverius** [comment]
I meant NCP as in nvim-complete-manager - sorry, I wasn't clear :)

**Comment by prabirshrestha** [comment]
That would be NCM.

By the way which language do you need tags for? It is better to have proper language completion rather than tags since tags can be very huge.

**Comment by Taverius** [comment]
Its more of a generic catchall.

There are various languages supported by (Exhuberant|Universal) Ctags that I use maybe twice a year each, where its really handy to have tag-completion at that time but totally not worth actually going and installing/configuring non-tag, non-ftype-omni completion for them.

For example, I have no need for clang-complete from n-c-m, but those handful of times yearly when I need to screw around in c being able to just `ctags -R` the project and have the tags in autocomplete is super-handy.

**Comment by prabirshrestha** [comment]
Initial source is done. You can find it at https://github.com/prabirshrestha/asyncomplete-tags.vim. We can continue the discussions there.

Currently there are no optimizations. Ideally it would be better to have an external program read the tags file and do the binary search so that vim wouldn't be blocked and vim can communicate via `job`. This means you can use any language to parse tags files and do the search as long as it can talk by stdout and stdin and is a long running server so don't need to keep reading the file. If you want to take a stab at it let me know.
