### ISSUE TITLE
Popup window reopen on <BS>, continuing typing and close if at the beginning of word.

### ISSUE THREAD

**Issue by mitinarseny** [prabirshrestha/asyncomplete.vim#195]
Firstly, let me thank you for developing this plugin! It is the only reason I didn't give up tweaking my dotfiles to make vim autocompletion work like in JetBrains IDEs.

As for the issue:
* popup window vanishes after pressing backspace
* popup window is not brought back on continuing typing
* autocompletion is called even with zero typed word characters

So, when I start tying in insert mode:
![image](https://user-images.githubusercontent.com/10659110/79077751-5194b080-7d0c-11ea-95c2-847eb1f29d84.png)
And then press <BS> to delete last typed symbol on the left of cursor. And popup suddenly vanishes:
![image](https://user-images.githubusercontent.com/10659110/79077816-b3edb100-7d0c-11ea-98ed-7b610b762372.png)
Retyping last deleted symbol does not brings popup back:
![image](https://user-images.githubusercontent.com/10659110/79077837-d1227f80-7d0c-11ea-8fd6-452ee6fa8968.png)
The only way to bring popup back is to delete current word:
![image](https://user-images.githubusercontent.com/10659110/79077864-05963b80-7d0d-11ea-9f4b-b50494253299.png)
And here we come to the the second issue: I do not want to trigger autocompletion for empty word. Is it possible to add support for customization of the length of prefix which triggers autocompletion?

I've skimmed source code and found [`b:asyncomplete_refresh_pattern`](https://github.com/prabirshrestha/asyncomplete.vim/blob/1f8d8ed26acd23d6bf8102509aca1fc99130087d/autoload/asyncomplete.vim#L288) which can be the possible solution, but I didn't manage the right value for this pattern.

In my `init.vim`:

```vim
  Plug 'prabirshrestha/async.vim'
  Plug 'prabirshrestha/vim-lsp'
    let g:lsp_diagnostics_enabled          = v:true
    let g:lsp_diagnostics_echo_cursor      = v:true
    let g:lsp_diagnostics_echo_delay       = 200
    let g:lsp_signs_enabled                = v:true
    let g:lsp_signs_error                  = { 'text': '>>' }
    let g:lsp_signs_warning                = { 'text': '--' }
    let g:lsp_signs_hint                   = { 'text': '..' }
    let g:lsp_virtual_text_enabled         = v:false
    let g:lsp_highlight_references_enabled = v:true
    let g:lsp_signature_help_enabled       = v:true
    let g:lsp_async_completion             = v:true

    " Close preview window with <esc>
    autocmd User lsp_float_opened nmap <buffer> <silent> <Esc>
      \ <Plug>(lsp-preview-close)
    autocmd User lsp_float_closed call lsp#ui#vim#references#highlight(v:false)
      \ | nunmap <buffer> <Esc>

    if executable('gopls')
      augroup LspGo
        autocmd!
        autocmd User lsp_setup call lsp#register_server({
          \ 'name': 'gopls',
          \ 'cmd': {server_info->['gopls']},
          \ 'whitelist': ['go'],
          \ })
        autocmd BufWritePre *.go LspDocumentFormatSync
      augroup END
    endif

  Plug 'prabirshrestha/asyncomplete.vim'
  Plug 'prabirshrestha/asyncomplete-lsp.vim'
    let g:asyncomplete_auto_popup       = v:true
    let g:asyncomplete_auto_completeopt = v:false

    set completeopt=menuone,noinsert,noselect

    function! s:on_lsp_buffer_enabled() abort
      setlocal omnifunc=lsp#complete
      setlocal signcolumn=yes

      highlight lspReference cterm=underline

      nnoremap <buffer> <silent> <C-]>                    <Cmd>LspDefinition<CR>
      inoremap <buffer> <silent> <C-]>                    <Cmd>LspDefinition<CR>
      nnoremap <buffer> <silent> <C-LeftMouse> <LeftMouse><Cmd>LspDefinition<CR>
      inoremap <buffer> <silent> <C-LeftMouse> <LeftMouse><Cmd>LspDefinition<CR>

      nnoremap <buffer> <Leader>lu <Cmd>LspReferences<CR>
      nnoremap <buffer> <Leader>lr <Cmd>LspRename<CR>
      nnoremap <buffer> <Leader>lh <Cmd>LspHover<CR>
    endfunction

    augroup lsp_install
      autocmd!
      autocmd User lsp_buffer_enabled call <SID>on_lsp_buffer_enabled()
      autocmd User lsp_complete_done  call asyncomplete#close_popup()
    augroup END
```

**Comment by BiochemLouis** [comment]
+1

Just tried switching from completor to asyncomplete for completion with ALE, I guess I have to go back for now.

**Comment by ii41** [comment]
Currently the matches are not cleared when the completion base stop matching the refresh pattern. I think this is something that should be eventually fixed in this plugin, but you can write a custom preprocessor as a workaround for now. `:h g:asyncomplete_preprocessor` and you can get an example preprocessor to get started with. Writing a preprocessor that sends an empty list to `asyncomplete#preprocess_complete` when `a:option['base']` is empty should be enough?

**Comment by prabirshrestha** [comment]
We need to add a `InsertCharPre` autocmd and then check `v:char`. Feel free to send a PR.

**Comment by ii41** [comment]
@prabirshrestha In `on_change` we have a piece of code deciding whether to start a completion based on min chars, refresh pattern and trigger characters. I think by reorganizing it we might be able to come up with a cleaner solution, so am doing some investigation. Something that's confusing me is why we want to disable popup when what's typed doesn't match the refresh pattern. When this happens ideally we don't have anything to show in a popup window, but even if we do, it should be fine to skip it as users don't expect to see a popup window here.

**Comment by prabirshrestha** [comment]
All in for reorganizing but I do still prefer to have last trigger char since that avoids using regex which makes the plugin fast and is optimized for LSP which uses trigger chars. This way I do know that if it matches trigger chars I know what lsp server or sources to call.

regex is still necessary for others cases.

Here is the design or internal workings of asyncomplete.vim. (I need to have some formal diagrams for this.)
https://github.com/prabirshrestha/asyncomplete.vim/pull/91#issuecomment-450770070. It was before I had min char support so now it is slightly complex. but if see the diagram gist of the flow is pretty simple. 

I do agree that onchange can be simplified. Most likely all we need is `InsertCharPre` and `TextChangedI`. I have been wanting to work on some redesign of asyncomplete to be smaller and bug free without api breaks but currently focused on other plugins such quickfix and vim-lsp.

 If you have charts or diagrams that will make it very easy to iterate. In fact the way I wrote asyncopmlete.vim was first draw charts in the ipad and then convert it to code. I'm more than happy to help out to code here too.

**Comment by ii41** [comment]
Okay. Guess I get the allowance to make some larger change. Great news for me.

**Comment by prabirshrestha** [comment]
Please try the latest master and let me know if it doesn't work.

**Comment by prabirshrestha** [comment]
@ii41 actually the PR regresses another feature so had to revert it for now. More details at https://github.com/prabirshrestha/asyncomplete.vim/pull/227#issuecomment-706812023.

Feel free to send another PR.
