### ISSUE TITLE
No autocomplete on <Tab>

### ISSUE THREAD

**Issue by savchenko** [prabirshrestha/asyncomplete.vim#263]
I have installed the following:

```vim
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
```
Despite the best effort, I can't trigger the completion menu via <kbd>\<Tab></kbd> in insert mode. Regular <kbd>\<C-n></kbd> works fine. Relevant excerpt from the `~/.vimrc`:

```vim
" Completion options
set completeopt=menuone,noinsert,noselect,preview

" Async-<Tab>-complete
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr>    pumvisible() ? asyncomplete#close_popup() : "\<cr>"

let g:asyncomplete_auto_completeopt = 1
let g:asyncomplete_enable_for_all = 1
let b:asyncomplete_enable = 1
let g:asyncomplete_auto_popup = 1

if executable('pyls')
    " pyls is installed
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->['pyls']},
        \ 'allowlist': ['python'],
        \ })
endif
```

Output of the `verbose imap <tab>`:

```vim
i  <Tab>       * pumvisible() ? "\<C-N>" : "\<Tab>"
        Last set from ~/.vimrc line 646
```

Any advice on how to debug?

```
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
```

Thank you.

**Comment by dbarnett** [comment]
That mapping is to let you page through the completion menu when it's open by pressing Tab. Sounds like you want Tab to *open* the completion menu when it wasn't previously open, instead of inserting tab/indent like normal? In that case you'd want a different mapping something like
```vim
imap <Tab> <Plug>(asyncomplete_force_refresh)
```
but then you'd lose the ability to indent by pressing Tab.

If you're just trying to figure out how to trigger completion results at all, they should pop up automatically when there are results to show since you have `g:asyncomplete_auto_popup` enabled, or you could set up a mapping to trigger `<Plug>(asyncomplete_force_refresh)`.
