### ISSUE TITLE
Vim9Script

### ISSUE THREAD

**Issue by pusewicz** [prabirshrestha/asyncomplete.vim#278]
Hey @prabirshrestha,

What are your thoughts about migrating `asyncomplete` to vim9script?

**Comment by prabirshrestha** [comment]
No plans to migrate. The bottleneck is not in vimscript, we already use `matchfuzzy` which is written in C. Most of the issue comes with converting existing items to vim item and those are issues with sources and not with asyncomplete.vim. If you are finding perf issues feel free to share more info.
